#import "./fragment.gql"
mutation updateOrganization(
    $id: ID!,
    $name: String!,
    $street: String!,
    $psc: String!,
    $city: String!,
    $country: String!,
    $ico: String!,
    $dic: String,
    $tel: String,
    $www: String,
    $type: String) {
    updateOrganization(
      id: $id
      name: $name,
      street: $street,
      psc: $psc,
      city: $city,
      country: $country,
      ico: $ico,
      dic: $dic,
      tel: $tel,
      www: $www,
      type: $type
      ) {
     ...OrganizationFragment
      
    }
  }